# This workflow will deploy the LZA in ADO
name: 3.sub-placement-lza-deployment

trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - '3.sub-placement/**'

stages:
  - stage: PRValidation
    displayName: 'PR Validation for Sub Placement'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: lint
        displayName: 'Lint Subscription-Placement Templates'
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - bash: |
              az bicep install
              az bicep version
            displayName: 'Install Bicep CLI'
          - bash: az bicep build --file ./3.sub-placement/main.bicep

      - job: SAST
        displayName: 'SAST Analysis'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - checkout: self
        - task: MicrosoftSecurityDevOps@1
          displayName: 'Run SAST Analysis'
          inputs:
            tools: 'checkov,templateanalyzer'
        workingDirectory: '3.sub-placement'

      - job: validate
        displayName: 'Validate Subscription-Placement Deployment'
        pool: 
          vmImage: 'ubuntu-latest'
        dependsOn: [lint, SAST]
        condition: succeeded()
        steps:
          - checkout: self
          - bash: |
              az bicep install
              az bicep version
            displayName: 'Install Bicep CLI'
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az config set bicep.use_binary_from_path=false --only-show-errors
                az deployment mg validate --name "ACA-$(Build.BuildId)" --location $(location) --template-file ./3.sub-placement/main.bicep --management-group-id $(management-group-id)

      - job: preview
        displayName: 'Preview Sub Placement Deployment'
        pool: 
          vmImage: 'ubuntu-latest'
        dependsOn: [lint, validate]
        condition: succeeded()
        steps:
          - checkout: self
          - bash: |
              az bicep install
              az bicep version
            displayName: 'Install Bicep CLI'
          - task: AzureCLI@2 
            inputs: 
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az config set bicep.use_binary_from_path=false --only-show-errors
                az deployment mg what-if \
                  --location $(location) \
                  --template-file ./3.sub-placement/main.bicep \
                  --management-group-id $(management-group-id)

  - stage: ManualDeployment
    displayName: 'Manual Deployment for Sub Placement'
    dependsOn: []
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: FinalWhatIf
        displayName: 'Run What-If before Deployment'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - bash: |
              az bicep install
              az bicep version
            displayName: 'Install Bicep CLI'

          - task: AzureCLI@2 
            displayName: 'Final What-If'
            inputs: 
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              failOnStandardError: true
              inlineScript: |
                az config set bicep.use_binary_from_path=false --only-show-errors
                az deployment mg what-if \
                  --location $(location) \
                  --template-file ./3.sub-placement/main.bicep \
                  --management-group-id $(management-group-id)

      - deployment: deploy
        displayName: 'Deploy Sub Placement'
        pool: 
          vmImage: 'ubuntu-latest'
        dependsOn: [FinalWhatIf]
        condition: succeeded()
        environment: 'alz-bicep-deployment'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - bash: |
                    az bicep install
                    az bicep version
                  displayName: 'Install Bicep CLI'

                - task: AzureCLI@2 
                  name: 'deploy'
                  displayName: 'Deploy Sub Placement'
                  inputs: 
                    azureSubscription: $(azureServiceConnection)
                    scriptType: bash
                    scriptLocation: inlineScript
                    failOnStandardError: true
                    inlineScript: |
                      az config set bicep.use_binary_from_path=false --only-show-errors
                      output=$(az deployment mg \
                      --location $(location) \
                      --template-file ./3.sub-placement/main.bicep \
                      --management-group-id $(management-group-id))
                      echo $output | jq .
                      echo "##[section]"