# This workflow will deploy the LZA in ADO
name: 6.cross-subscription-lza-deployment

trigger: none
pr: none

variables:
  - group: 'CrossSubscription'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The lint job performs linting on the bicep code
  - job: lint
    pool: 
      vmImage: 'ubuntu-latest'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under so your job can access it
      - checkout: self
      - bash: |
          az bicep install
          az bicep version
        displayName: 'Install Bicep CLI'

      # Runs the Bicep linter to ensure build is successful
      - bash: az bicep build --file ./6.cross-subscription/main.bicep

  - job: validate
    pool: 
      vmImage: 'ubuntu-latest'
    dependsOn: [lint]
    steps:
      - checkout: self
      - bash: |
          az bicep install
          az bicep version
        displayName: 'Install Bicep CLI'
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          addSpnToEnvironment: true
          failOnStandardError: false
          inlineScript: |
            az config set bicep.use_binary_from_path=false
            az stack mg validate \
              --name "cross-subscription-deployment-stack" \
              --location $(location) \
              --management-group-id $(management-group-id) \
              --template-file ./6.cross-subscription/main.bicep \
              --parameters paramvnetPeeringsVNetIDs="$(paramvnetPeeringsVNetIDs)" \
                           manageddevopspoolVnetID="$(manageddevopspoolVnetID)" \
                           paramserviceIds="$(serviceIds)" \
              --deny-settings-mode none --action-on-unmanage deleteResources \
              --output table

  - job: deploy
    pool: 
      vmImage: 'ubuntu-latest'
    dependsOn: [validate]
    steps:
      - checkout: self
      - bash: |
          az bicep install
          az bicep version
        displayName: 'Install Bicep CLI'
      - task: AzureCLI@2 
        name: deploy
        inputs: 
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          addSpnToEnvironment: true
          failOnStandardError: true
          inlineScript: |
            az config set bicep.use_binary_from_path=false
            output=$(az stack mg create \
              --name "cross-subscription-deployment-stack" \
              --location $(location) \
              --management-group-id $(management-group-id) \
              --template-file ./6.cross-subscription/main.bicep \
              --parameters paramvnetPeeringsVNetIDs="$(paramvnetPeeringsVNetIDs)" \
                           manageddevopspoolVnetID="$(manageddevopspoolVnetID)" \
                           paramserviceIds="$(serviceIds)" \
              --deny-settings-mode none --action-on-unmanage deleteResources --yes)
            echo "Full Bicep Deployment Output:"
            echo $output | jq .