# This workflow will deploy cross-subscription resources
name: 6.cross-subscription-lza-deployment

trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - '6.cross-subscription/**'

parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - systemtest_manual
      - systemtest_auto
      - uat
      - pre_prod
      - production
      - dw
  - name: deploy_dw_private_endpoints
    displayName: 'Deploy DW Function App Private Endpoints'
    type: boolean
    default: false

stages:
  - stage: PRValidation
    displayName: 'PR Validation for Cross Subscription'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: setup
        displayName: 'Checkout and Install Bicep'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - bash: |
              az bicep install
              az bicep version
            displayName: 'Install Bicep CLI'

      - job: lint
        displayName: 'Lint Cross Subscription Templates'
        pool:
          vmImage: 'ubuntu-latest'
        dependsOn: [setup]
        steps:
          - bash: az bicep build --file ./6.cross-subscription/main.bicep
            displayName: 'Build Bicep Template'

      - job: SAST
        displayName: 'SAST Analysis'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: MicrosoftSecurityDevOps@1
          displayName: 'Run SAST Analysis'
          inputs:
            tools: 'checkov,templateanalyzer'
            artifactName: 'CodeAnalysisLogs'
          env:
            GDN_RUN_WORKINGDIRECTORY: '6.cross-subscription'

      - job: validate
        displayName: 'Validate Cross Subscription Deployment'
        pool:
          vmImage: 'ubuntu-latest'
        dependsOn: [setup, lint, SAST]
        condition: succeeded()
        variables:
          - group: CrossSubscription-${{ parameters.env }}
        steps:
          - task: AzureCLI@2
            displayName: 'Validate Bicep Template'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az config set bicep.use_binary_from_path=false --only-show-errors
                az deployment mg validate \
                  --name "CrossSubscription-$(Build.BuildId)" \
                  --location $(location) \
                  --management-group-id $(management-group-id) \
                  --template-file ./6.cross-subscription/main.bicep \
                  --parameters ./6.cross-subscription/main.parameters.bicepparam \
                              paramvnetPeeringsVNetIDs=$(paramvnetPeeringsVNetIDs) \
                              manageddevopspoolVnetID=$(manageddevopspoolVnetID) \
                              paramserviceIds=$(paramserviceIds) \
                              environment='${{ parameters.env }}' \
                              storageSubscriptionId="$(storageSubscriptionId)" \
                              devboxSubscriptionId="$(devboxSubscriptionId)" \
                              deployDwPrivateEndpoints=${{ parameters.deploy_dw_private_endpoints }} \
                              dwFunctionAppId=$(dwFunctionAppId) \
                              dwFunctionAppSubscriptionId="$(dwFunctionAppSubscriptionId)" \
                              dwNetworkingResourceGroup="$(dwNetworkingResourceGroup)" \
                              dwVnetName="$(dwVnetName)" \
                              dwPrivateEndpointSubnetName="$(dwPrivateEndpointSubnetName)" \
                              dwEnvironment="$(dwEnvironment)" \
                              enableDevBoxSqlReplicaEndpoints=$(enableDevBoxSqlReplicaEndpoints) \
                              replicaSqlServerResourceIds="$(replicaSqlServerResourceIds)" \
                              replicaSqlServerNames="$(replicaSqlServerNames)" \
                              devBoxSecondaryVNetIds="$(devBoxSecondaryVNetIds)"

      - job: preview
        displayName: 'Preview Cross Subscription Deployments'
        pool:
          vmImage: 'ubuntu-latest'
        dependsOn: [setup, lint, validate]
        condition: succeeded()
        variables:
          - group: CrossSubscription-${{ parameters.env }}
        steps:
          - task: AzureCLI@2
            displayName: 'What-If Analysis'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az config set bicep.use_binary_from_path=false --only-show-errors
                az deployment mg what-if \
                  --location $(location) \
                  --template-file ./6.cross-subscription/main.bicep \
                  --management-group-id $(management-group-id) \
                  --parameters ./6.cross-subscription/main.parameters.bicepparam \
                              paramvnetPeeringsVNetIDs=$(paramvnetPeeringsVNetIDs) \
                              manageddevopspoolVnetID=$(manageddevopspoolVnetID) \
                              paramserviceIds=$(paramserviceIds) \
                              environment='${{ parameters.env }}' \
                              storageSubscriptionId="$(storageSubscriptionId)" \
                              devboxSubscriptionId="$(devboxSubscriptionId)" \
                              deployDwPrivateEndpoints=${{ parameters.deploy_dw_private_endpoints }} \
                              dwFunctionAppId=$(dwFunctionAppId) \
                              dwFunctionAppSubscriptionId="$(dwFunctionAppSubscriptionId)" \
                              dwNetworkingResourceGroup="$(dwNetworkingResourceGroup)" \
                              dwVnetName="$(dwVnetName)" \
                              dwPrivateEndpointSubnetName="$(dwPrivateEndpointSubnetName)" \
                              dwEnvironment="$(dwEnvironment)" \
                              enableDevBoxSqlReplicaEndpoints=$(enableDevBoxSqlReplicaEndpoints) \
                              replicaSqlServerResourceIds="$(replicaSqlServerResourceIds)" \
                              replicaSqlServerNames="$(replicaSqlServerNames)" \
                              devBoxSecondaryVNetIds="$(devBoxSecondaryVNetIds)"

  # Environment-specific deployment stages

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: dev
      displayName: 'Deploy to Development'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: systemtest_manual
      displayName: 'Deploy to System Test (Manual)'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: systemtest_auto
      displayName: 'Deploy to System Test (Auto)'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: uat
      displayName: 'Deploy to UAT'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: pre_prod
      displayName: 'Deploy to Pre-Production'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: production
      displayName: 'Deploy to Production'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}

  - template: templates/cross-subscription-deployment-stage.yaml
    parameters:
      environmentName: dw
      displayName: 'Deploy to Data Warehouse'
      deployDwPrivateEndpoints: ${{ parameters.deploy_dw_private_endpoints }}
      selectedEnvironment: ${{ parameters.env }}
